### ISSUE TITLE
ChainedDeconstruction Crash

### ISSUE THREAD

**Issue by honorgog** [EtiamNullam/Etiam-ONI-Modpack#12] opened 2020-07-10 03:49 UTC
ONI disables ChainedDeconstruction and Deconstructable POI Props after this crash.
Attached is my output_log.txt file as requested:

[output_log.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4900681/output_log.txt)

**Comment by EtiamNullam** [comment] 2020-07-10 15:38
Thanks! Sadly I can't reproduce it. Does it happen every time you deconstruct something specific?

I looked and there isn't anything that would lead to this kind of error. Maybe you are getting wrong version of `Deconstructable POI Props` from Steam Workshop?

Let me know if you have any more info about this.

**Comment by honorgog** [comment] 2020-07-10 22:37
Unfortunately, it's not easily replicated.  I've attempted to note what I'm doing at multi times but something new is happening during each time.  It's random which is the worst sort of problem to debug.  I've installed the Mod Update addon but that is now crashing due to the latest patch.  Before it died though, it reported that Deconstructable POI Props was the latest version.  I'm continuing without Deconstructable POI Props to see if it happens again.  I will let you know if ChainedDeconstruction crashes again.

**Comment by scott4dges** [comment] 2020-07-11 01:59
I have also experienced this crash where ChainedDestruction and Deconstructable POI Props are disabled after a crash. I can confirm I'm running v2.2.1.0 of this mod.

This has happened a half-dozen times in the past couple days. At the time of the latest crash, I was breaking down a series of power wires along with some automation wires. In the Steam Workshop comments on your mod, I noticed someone else saying it didn't work with Automation wires? Not sure if this is related?

Also, I don't know where to find the output.log file you mentioned in the Steam Workshop comments to another user. If the crash happens again, I'll try and screenshot and provide a log.

**Comment by honorgog** [comment] 2020-07-11 02:51
You can find the output_log.txt file within your "C:\User\<username>\AppData\LocalLow\Klei\Oxygen Not Included" directory.

Be sure to grab this before restarting ONI as it will delete the file.  Also, AppData is normally hidden so you may need to enable "show hidden files" to see it.

**Comment by scott4dges** [comment] 2020-07-11 05:19
Thanks for the info. I just got another crash, this time I wasn't focused on anything specifically, but it's possible my dupes were doing some construction/destruction elsewhere (clearing out biomes).

Anyway, I don't know how to read these logs, but I kept seeing this exception:

`ArgumentException: Accessing mismatched handle version` 

It appears 16,676 times (according to Notepad++), but I don't know if that's related to your mod. There are a couple variations of these, but here's the most common:

`ArgumentException: Accessing mismatched handle version. Expected version=245 but got version=244
  at HandleVector 1[T].UnpackHandle (HandleVector 1+Handle[T] handle, System.Byte& version, System.Int32& index) [0x0005c] in <1dcc11867b524f7cb2488468843e982e>:0 
  at HandleVector 1[T].GetItem (HandleVector1+Handle[T] handle) [0x00000] in <1dcc11867b524f7cb2488468843e982e>:0 
  at Klei.CallbackInfo.Release () [0x00012] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at World.UpdateCellInfo (System.Collections.Generic.List 1[T] solidInfo, System.Collections.Generic.List 1[T] callbackInfo, System.Int32 num_solid_substance_change_info, Sim+SolidSubstanceChangeInfo* solid_substance_change_info, System.Int32 num_liquid_change_info, Sim+LiquidChangeInfo* liquid_change_info) [0x000c8] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.UnsafeSim200ms (System.Single dt) [0x00045] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.SimEveryTick (System.Single dt) [0x00091] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.Update () [0x00120] in <a8d8cafbcd164cda9f477d36796bfc75>:0`
 
`(Filename: <1dcc11867b524f7cb2488468843e982e> Line: 0)`

Here is a link to the output log file: https://tinyurl.com/y8efzrmo

**Comment by EtiamNullam** [comment] 2020-07-11 16:21
I think this is the important part:

```
[04:57:56.514] [1] [INFO] ChainedDeconstruction's patched_method Deconstructable.TriggerDestroy matched in the stack trace, adding to referenced mods list
[04:57:56.515] [1] [INFO] Deconstructable POI Props's patched_method Deconstructable.TriggerDestroy matched in the stack trace, adding to referenced mods list
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Object.GetName(UnityEngine.Object)
  at UnityEngine.Object.get_name () [0x00001] in <a35d771e78bd4d75a6f3aedeaad4d1ed>:0 
  at DeconstructableProps.Patches__Deconstructable__TriggerDestroy.Prefix (Deconstructable __instance, System.Single temperature, System.Byte disease_idx, System.Int32 disease_count) [0x00035] in <19d6273099e94dc6a9d983db811a3ce1>:0 
  at (wrapper dynamic-method) Deconstructable.TriggerDestroy_Patch2(object,single,byte,int)
  at Deconstructable+<>c__DisplayClass11_0.<OnCompleteWork>b__0 () [0x00000] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Klei.CallbackInfo.Release () [0x00046] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at World.UpdateCellInfo (System.Collections.Generic.List`1[T] solidInfo, System.Collections.Generic.List`1[T] callbackInfo, System.Int32 num_solid_substance_change_info, Sim+SolidSubstanceChangeInfo* solid_substance_change_info, System.Int32 num_liquid_change_info, Sim+LiquidChangeInfo* liquid_change_info) [0x000c8] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.UnsafeSim200ms (System.Single dt) [0x00045] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.SimEveryTick (System.Single dt) [0x00054] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
  at Game.Update () [0x00120] in <a8d8cafbcd164cda9f477d36796bfc75>:0 
 
(Filename: <a35d771e78bd4d75a6f3aedeaad4d1ed> Line: 0)
```

So it looks both `ChainedDeconstruction` and `Destructable POI props` patch target the same method in game:
- `Destructable POI props` runs before `Deconstructable.TriggerDestroy` (Prefix)
- `ChainedDeconstruction` runs after `Deconstructable.TriggerDestroy` (Postfix)

More info about the Harmony execution flow:
https://github.com/pardeike/Harmony/wiki/Execution-Flow

**Comment by scott4dges** [comment] 2020-07-11 18:43
> I think this is the important part: (Snip) <

Thank you for looking at this. I've posted info from your comment in the Steam Workshop on the Destructable POI Prop mod page. 

Not sure if there is some way to create a compatibility patch for these two mods to coexist, or if it's just a basic function that can't be called in the same way by two different mods (I'm not a coder myself).

Anyway, I guess in the meantime it's a matter of choosing which mod is more important. I'll definitely choose ChainedDestruction. :)

**Comment by EtiamNullam** [comment] 2020-07-11 21:47
@scott4dges: Harmony is designed to have multiple mods patch one method, so its not the problem on its own.

I've never experienced a crash you are all talking about despite I had `Destructable POI Props` installed most of the time.

According to comments section on `Destructable POI Props` steam workshop page there was previously an issue where deconstructing bioscan door crashed the game - check if it crashes for you, if it does you need to get new version of `Destructable POI Props`. Its a common problem with Steam Workshop and I'm pretty sure [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) was made to make it easier to deal with this (sadly this mod seems currently broken).

Let me know if anyone has more info about this problem.

**Comment by hrottipharmd** [comment] 2020-07-27 01:37
Unsure if this helps at all.  Mod load list was ChainedDeconstruction then Deconstructable POI Props.  Was demoing a whole mess of tiles/pipes. 

[crash.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4979390/crash.txt)

**Comment by hrottipharmd** [comment] 2020-07-28 22:56
> Unsure if this helps at all. Mod load list was ChainedDeconstruction then Deconstructable POI Props. Was demoing a whole mess of tiles/pipes.
> 
> [crash.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4979390/crash.txt)

Have tried to recreate crash with Deconstructable POI Props unloaded, several hundred cycles of building random tiles/demo commands.  No crashes.  Conflict seems to occur when both ChainedDeconstruction and Deconstructable POI Props are loaded.

**Comment by Giovanni-Boss** [comment] 2021-01-13 22:09
First, let me resume my previous comments on the mod page on Steam, sou you have the information here, as you requested.

Everything below according to my own experience, of course.
- Crashes tended to be rare early game, became increasingly frequent after a thousand cycles or so;
- Disabling the Deconstructible POI mod stopped the crashes from occuring entirely;
- Most early crashes happened while trying to chain deconstruct stuff near POI affected by the other mod. Namely, the Mosaic Tiles, as far as I can remember;
- I can't recall the game ever crashing while chain deconstructing any piping, either gas or liquid. I also believe it never crashed deconstructing power wires, but I'm not completely sure;
-  Chain deconstructing tiles usually is the thing that triggers crashes. 

I'll enable the Deconstructible POI mod again and pull my current save from the cloud to send it to you.

**Comment by Giovanni-Boss** [comment] 2021-01-14 21:58
[Loveliest Cantaloupe Cycle 2020.zip](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/5817195/Loveliest.Cantaloupe.Cycle.2020.zip)

**Comment by Giovanni-Boss** [comment] 2021-01-15 00:53
I've played this save until I crashed. I ended up saving just before the crash, I kind of felt in my bones it was coming. Still, I don't think it is repeatable. The game usually handles fine for a short while after reopening.

I tried to deconstruct two clusters of three linked Granite tiles. The first went fine, the second crashed the game. 

Here's the details I copied to the clipboard. Hope that helps. I can keep playing with both mods to copy the crash details to the clipboard then paste them here, if you so wish. Otherwise, I'll keep the Deconstructible POI mod disabled.


NullReferenceException

UnityEngine.Object.get_name () (at <b8388ffefd6046f8a7b4080349da72eb>:0)
DeconstructableProps.Patches__Deconstructable__TriggerDestroy.Prefix (Deconstructable __instance, System.Single temperature, System.Byte disease_idx, System.Int32 disease_count) (at <19d6273099e94dc6a9d983db811a3ce1>:0)
(wrapper dynamic-method) Deconstructable.TriggerDestroy_Patch2(object,single,byte,int)
Deconstructable+<>c__DisplayClass11_0.<OnCompleteWork>b__0 () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Klei.CallbackInfo.Release () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
World.UpdateCellInfo (System.Collections.Generic.List`1[T] solidInfo, System.Collections.Generic.List`1[T] callbackInfo, System.Int32 num_solid_substance_change_info, Sim+SolidSubstanceChangeInfo* solid_substance_change_info, System.Int32 num_liquid_change_info, Sim+LiquidChangeInfo* liquid_change_info) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Game.UnsafeSim200ms (System.Single dt) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Game.SimEveryTick (System.Single dt) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Game.Update () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)

**Comment by EtiamNullam** [comment] 2021-01-15 19:40
@Giovanni-Boss This save is very useful, thanks! I can consistently crash the game now just by deconstructing some tiles in it.

So it looks the problem is that `Deconstructable POI Props` is trying to access name of `Deconstructable` object and this object does not exist so we are getting a `NullReferenceException` and its crashing the game.

I've added a simple patch for `TriggerDestroy` (that both our mods hook into) that will run with higher priority (before) `Deconstructable POI Props` patch and stop execution if `Deconstructable` instance is null. Seems to work fine now.

**Comment by EtiamNullam** [comment] 2021-01-15 19:45
I ran into a minor problem while updating the mod but it should be fine now.

Anyway give it a try and let me know if it helps. New patch should be available at Steam Workshop very soon.

**Comment by Giovanni-Boss** [comment] 2021-01-15 20:14
Always glad to help. Awesome that you managed to pinpointed the issue!

> 
> 
> @Giovanni-Boss This save is very useful, thanks! I can consistently crash the game now just by deconstructing some tiles in it.
> 
> So it looks the problem is that `Deconstructable POI Props` is trying to access name of `Deconstructable` object and this object does not exist so we are getting a `NullReferenceException` and its crashing the game.
> 
> I've added a simple patch for `TriggerDestroy` (that both our mods hook into) that will run with higher priority (before) `Deconstructable POI Props` patch and stop execution if `Deconstructable` instance is null. Seems to work fine now.

**Comment by EtiamNullam** [comment] 2021-01-16 08:57
To be honest its something that could easily be avoided by developer of `Deconstructable POI Props` and it probably might still crash without `ChainedDeconstruction` in some rare cases.

Thanks everyone for helping me resolve the problem.

I'm closing the issue for now. Let me know if there is still something not right about it.

**Closed as completed by EtiamNullam** 2021-01-16 08:57 UTC

**Comment by hrottipharmd** [comment] 2021-01-26 03:16
I just saw this email chain! I really should have not linked it to my
junkmail... Apologies! I'm glad you all were able to figure out what I
couldn't pinpoint either!
